# Generated by Django 5.2.8 on 2025-11-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('platform', models.CharField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('other', 'Other')], max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_url', models.URLField(blank=True, max_length=1000)),
                ('summary', models.TextField(blank=True)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='meeting_pdfs/')),
                ('pdf_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='meetings_me_start_t_56d2de_idx'), models.Index(fields=['meeting_id'], name='meetings_me_meeting_c082af_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('title', 'Title'), ('summary', 'Summary'), ('transcript', 'Transcript'), ('decision', 'Decision'), ('action_item', 'Action Item')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_indices', to='meetings.meeting')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type'], name='meetings_se_content_3ec35e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('sequence', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='meetings.meeting')),
            ],
            options={
                'ordering': ['sequence', 'timestamp'],
                'indexes': [models.Index(fields=['meeting', 'sequence'], name='meetings_tr_meeting_8b67a6_idx')],
            },
        ),
    ]
