import PDFDocument from 'pdfkit';
import { Storage } from '@google-cloud/storage';
import fs from 'fs';
import path from 'path';
import { logger } from '../utils/logger';

// Initialize cloud storage (can be AWS S3, Azure Blob, or GCS)
const storage = process.env.GCS_BUCKET
  ? new Storage()
  : null;

interface PDFContent {
  title: string;
  date: Date;
  summary: string;
  actions: Array<{
    text: string;
    assignee?: string;
    dueDate?: Date;
  }>;
  attendees: string[];
  transcript?: string;
}

/**
 * Generate professional meeting PDF
 */
export async function generateMeetingPDF(
  meetingId: string,
  content: PDFContent
): Promise<string> {
  try {
    logger.info(`Generating PDF for meeting: ${meetingId}`);
    
    const filename = `meeting-${meetingId}-${Date.now()}.pdf`;
    const tempPath = path.join('/tmp', filename);
    
    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });
    
    const stream = fs.createWriteStream(tempPath);
    doc.pipe(stream);
    
    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('Meeting Summary', { align: 'center' });
    
    doc.moveDown(0.5);
    
    // Meeting details
    doc
      .fontSize(12)
      .font('Helvetica')
      .text(`Date: ${content.date.toLocaleString()}`, { align: 'center' });
    
    doc.moveDown(2);
    
    // Title
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text(content.title);
    
    doc.moveDown(1);
    
    // Attendees section
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('Attendees');
    
    doc.moveDown(0.5);
    
    doc
      .fontSize(11)
      .font('Helvetica');
    
    content.attendees.forEach(attendee => {
      doc.text(`• ${attendee}`);
    });
    
    doc.moveDown(1.5);
    
    // Summary section
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('Summary');
    
    doc.moveDown(0.5);
    
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(content.summary, {
        align: 'justify',
        lineGap: 4,
      });
    
    doc.moveDown(1.5);
    
    // Action items section
    if (content.actions.length > 0) {
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Action Items');
      
      doc.moveDown(0.5);
      
      doc.fontSize(11).font('Helvetica');
      
      content.actions.forEach((action, index) => {
        const actionText = `${index + 1}. ${action.text}`;
        const assigneeText = action.assignee ? ` (Assigned to: ${action.assignee})` : '';
        const dueDateText = action.dueDate
          ? ` [Due: ${action.dueDate.toLocaleDateString()}]`
          : '';
        
        doc.text(`${actionText}${assigneeText}${dueDateText}`, {
          lineGap: 6,
        });
        doc.moveDown(0.5);
      });
      
      doc.moveDown(1);
    }
    
    // Transcript section (optional, if available)
    if (content.transcript) {
      doc.addPage();
      
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Full Transcript');
      
      doc.moveDown(0.5);
      
      doc
        .fontSize(10)
        .font('Courier')
        .text(content.transcript, {
          align: 'left',
          lineGap: 3,
        });
    }
    
    // Footer with page numbers
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      
      doc
        .fontSize(9)
        .font('Helvetica')
        .text(
          `Page ${i + 1} of ${pages.count}`,
          50,
          doc.page.height - 50,
          {
            align: 'center',
          }
        );
      
      doc.text(
        `Generated by Sistec on ${new Date().toLocaleString()}`,
        50,
        doc.page.height - 35,
        {
          align: 'center',
        }
      );
    }
    
    // Finalize PDF
    doc.end();
    
    // Wait for stream to finish
    await new Promise<void>((resolve, reject) => {
      stream.on('finish', () => resolve());
      stream.on('error', reject);
    });
    
    // Upload to cloud storage
    let pdfUrl: string;
    
    if (storage && process.env.GCS_BUCKET) {
      const bucket = storage.bucket(process.env.GCS_BUCKET);
      const file = bucket.file(`meetings/${filename}`);
      
      await bucket.upload(tempPath, {
        destination: file,
        metadata: {
          contentType: 'application/pdf',
          metadata: {
            meetingId,
          },
        },
      });
      
      // Make file publicly accessible (or use signed URLs)
      await file.makePublic();
      
      pdfUrl = `https://storage.googleapis.com/${process.env.GCS_BUCKET}/meetings/${filename}`;
      
      // Clean up temp file
      fs.unlinkSync(tempPath);
    } else {
      // Local storage fallback
      const publicDir = path.join(process.cwd(), 'public', 'pdfs');
      
      if (!fs.existsSync(publicDir)) {
        fs.mkdirSync(publicDir, { recursive: true });
      }
      
      const publicPath = path.join(publicDir, filename);
      fs.renameSync(tempPath, publicPath);
      
      pdfUrl = `/pdfs/${filename}`;
    }
    
    logger.info(`PDF generated successfully: ${pdfUrl}`);
    
    return pdfUrl;
  } catch (error) {
    logger.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF');
  }
}

/**
 * Generate policy PDF with approvals and version history
 */
export async function generatePolicyPDF(
  policyId: string,
  content: {
    title: string;
    version: string;
    effectiveDate: Date;
    content: string;
    approvals: Array<{
      approver: string;
      date: Date;
      comments?: string;
    }>;
  }
): Promise<string> {
  try {
    const filename = `policy-${policyId}-v${content.version}-${Date.now()}.pdf`;
    const tempPath = path.join('/tmp', filename);
    
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
    });
    
    const stream = fs.createWriteStream(tempPath);
    doc.pipe(stream);
    
    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('Organization Policy', { align: 'center' });
    
    doc.moveDown(2);
    
    // Policy details
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text(content.title);
    
    doc.moveDown(0.5);
    
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(`Version: ${content.version}`)
      .text(`Effective Date: ${content.effectiveDate.toLocaleDateString()}`);
    
    doc.moveDown(2);
    
    // Policy content
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(content.content, {
        align: 'justify',
        lineGap: 4,
      });
    
    // Approvals section
    if (content.approvals.length > 0) {
      doc.addPage();
      
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Approvals');
      
      doc.moveDown(1);
      
      doc.fontSize(11).font('Helvetica');
      
      content.approvals.forEach(approval => {
        doc
          .text(`Approved by: ${approval.approver}`)
          .text(`Date: ${approval.date.toLocaleDateString()}`);
        
        if (approval.comments) {
          doc.text(`Comments: ${approval.comments}`);
        }
        
        doc.moveDown(1);
      });
    }
    
    // Footer
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);
      
      doc
        .fontSize(9)
        .font('Helvetica')
        .text(
          `Page ${i + 1} of ${pages.count}`,
          50,
          doc.page.height - 50,
          { align: 'center' }
        );
    }
    
    doc.end();
    
    await new Promise<void>((resolve, reject) => {
      stream.on('finish', () => resolve());
      stream.on('error', reject);
    });
    
    // Upload logic (similar to meeting PDF)
    let pdfUrl: string;
    
    if (storage && process.env.GCS_BUCKET) {
      const bucket = storage.bucket(process.env.GCS_BUCKET);
      const file = bucket.file(`policies/${filename}`);
      
      await bucket.upload(tempPath, {
        destination: file,
        metadata: { contentType: 'application/pdf' },
      });
      
      await file.makePublic();
      pdfUrl = `https://storage.googleapis.com/${process.env.GCS_BUCKET}/policies/${filename}`;
      fs.unlinkSync(tempPath);
    } else {
      const publicDir = path.join(process.cwd(), 'public', 'pdfs');
      if (!fs.existsSync(publicDir)) {
        fs.mkdirSync(publicDir, { recursive: true });
      }
      const publicPath = path.join(publicDir, filename);
      fs.renameSync(tempPath, publicPath);
      pdfUrl = `/pdfs/${filename}`;
    }
    
    logger.info(`Policy PDF generated: ${pdfUrl}`);
    return pdfUrl;
  } catch (error) {
    logger.error('Policy PDF generation error:', error);
    throw new Error('Failed to generate policy PDF');
  }
}
